export const FETCH_LIST_FILMS    = 'FETCH_LIST_FILMS';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_SIMILAR_FILMS = 'FETCH_SIMILAR_FILMS';
export const CLEAR_MOVIES_LIST   = 'CLEAR_MOVIES_LIST';